LearnMVC/Controllers/PaymentGatewayTransactionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using LearnMVC.Models;

public class PaymentGatewayTransactionController : Controller
{
    AppDataConnectionEntity connectionEntity = new AppDataConnectionEntity();
    
    [HttpGet]
    public ActionResult PaymentPage()
    {
        return View();
    }

    [HttpPost]
    public void PaymentPage(PaymentModel payment)
    {
        try
        {
            string firstname = payment.fname;
            string amount = payment.itemamount;
            string productinfo = payment.iteminfo;
            string email = payment.email;
            int phone = 97915;

            string surl = ConfigurationManager.AppSettings["paysuccessurl"].ToString();
            string furl = ConfigurationManager.AppSettings["payfailureurl"].ToString();
            string key = ConfigurationManager.AppSettings["MERCHANT_KEY"].ToString();
            string salt = ConfigurationManager.AppSettings["MERCHANT_SALT"].ToString();
            string txnid = Generatetransid();
            string serviceprovider = "payu_paisa";

            connectionEntity.RecordPaymentDetails(txnid, "", firstname, amount, email, phone.ToString(), "PAY U", serviceprovider, "");

            RemotePost remotepay = new RemotePost();

            remotepay.Url = ConfigurationManager.AppSettings["PAYU_BASE_URL"].ToString();
            remotepay.Add("key", key);
            remotepay.Add("txnid", txnid);
            remotepay.Add("amount", amount);
            remotepay.Add("firstname", firstname);
            remotepay.Add("productinfo", productinfo);
            remotepay.Add("email", email);
            remotepay.Add("phone", phone.ToString());
            remotepay.Add("surl", surl);
            remotepay.Add("furl", furl);
            remotepay.Add("service_provider", serviceprovider);
   
            string hashtext = key + "|" + txnid + "|" + amount + "|" + productinfo + "|" + firstname + "|" + email + "|||||||||||" + salt;
            string hash = Generatehashid(hashtext);
            remotepay.Add("hash", hash);

            remotepay.Post();
        }
        catch (Exception)
        {
            throw;
        }
    }

    public ActionResult PaymentStatus(FormCollection form)
    {
        try
        {
            string merc_hash_string = string.Empty;
            string merc_hash = string.Empty;
            string order_id = string.Empty;
            string hash_seq = ConfigurationManager.AppSettings["hashSequence"].ToString();

            if(form["status"].ToString() == "success")
            {
                connectionEntity.RecordPaymentDetails(
                    Request.Form["txnid"],
                    "",
                    Request.Form["firstname"],
                    Request.Form["amount"],
                    Request.Form["email"],
                    Request.Form["phone"],
                    "PAY U",
                    "payu_paisa",
                    "Payment Successful");

                ViewBag.Name = Request.Form["firstname"];
                ViewBag.Amount = Request.Form["amount"];
                ViewBag.OrderID = Request.Form["txnid"];
                ViewBag.Transtatus = "Payment is successful";
                //}
            }
            else
            {
                ViewBag.Transtatus = "Payment is failed";
                Response.Write("Hash value did not matched");
            }
        }
        catch(Exception ex)
        {
            Response.Write("<span style='color:red'>" + ex.Message + "</span>");
        }
        return View();
    }
    #region TxnID and Hash Request Method
    private string Generatetransid()
    {
        Random random = new Random();
        string hash = Generatehashid(random.ToString() + DateTime.Now);
        string transid = hash.ToString().Substring(0, 30);

        return transid;
    }
    private string Generatehashid(string text)//Generate Hash 512
    {
        string hex = "";
        byte[] message = Encoding.UTF8.GetBytes(text);

        UnicodeEncoding unicode = new UnicodeEncoding();
        SHA512Managed hashstring = new SHA512Managed();
        byte[] hashvalue;
        hashvalue = hashstring.ComputeHash(message);

        foreach (byte x in hashvalue)
        {
            hex += String.Format("{0:x2}", x);
        }

        return hex;
    }
    #endregion

    #region Payment - Post Method
    public class RemotePost
    {
        private System.Collections.Specialized.NameValueCollection Collection = new System.Collections.Specialized.NameValueCollection();

        public string Url = "";
        public string Method = "post";
        public string FormName = "PaymentPage";

        public void Add(string name, string value)
        {
            Collection.Add(name, value);
        }

        public void Post()
        {
            System.Web.HttpContext.Current.Response.Clear();
            System.Web.HttpContext.Current.Response.Write("<html><head>");

            System.Web.HttpContext.Current.Response.Write(string.Format("</head><body onload=\"document.{0}.submit()\">", FormName));
            System.Web.HttpContext.Current.Response.Write(string.Format("<form name=\"{0}\" method=\"{1}\" action=\"{2}\" >", FormName, Method, Url));

            for (int i = 0; i < Collection.Keys.Count; i++)
            {
                System.Web.HttpContext.Current.Response.Write(
                    string.Format("<input name=\"{0}\" type=\"hidden\" value=\"{1}\">",
                    Collection.Keys[i], Collection[Collection.Keys[i]])
                    );
            }

            System.Web.HttpContext.Current.Response.Write("</form>");
            System.Web.HttpContext.Current.Response.Write("</body></html>");

            System.Web.HttpContext.Current.Response.End();
        }
    }

    #endregion 

    private string EncodeDecode(string text, string Type)
    {

        string result = "";
        if(Type == "Encode")
        {
            byte[] message = Encoding.UTF8.GetBytes(text);

            UnicodeEncoding unicode = new UnicodeEncoding();
            SHA512Managed hashstring = new SHA512Managed();
            byte[] hashvalue;

            hashvalue = hashstring.ComputeHash(message);
            foreach (byte x in hashvalue)
            {
                result += String.Format("{0:x2}", x);
            }
        }
        
        return result;
    }
}

LearnMVC/Views/PaymentGatewayTransaction/PaymentPage.cshtml
@model LearnMVC.Models.PaymentModel

@{
    ViewBag.Title = "PaymentPage";
}
<br />
@using (Html.BeginForm("PaymentPage", "PaymentGatewayTransaction", FormMethod.Post))
{
    <div id="paymentpage">
        <img id="payimage" class=" pull-left" src="~/Content/Images/paymentsecure.png" />
        <img id="payimage" class=" pull-right" src="~/Content/Images/payu.png" />
        <h2 id="headings">Payment Checkout</h2>
        <hr  style="border-top:2px solid grey;width:65%" />
        <div class="container">
            <div id="paydetails" class="row">
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <h3>Customer Details</h3>
                    <br />
                    <label class="control-label" for="fname">Name</label>
                    <input id="fname" type="text" name="fname" class="form-control" value="Sai Bhargav" placeholder="Name" />
                    <label class="control-label" for="amt">Amount</label>
                    <input id="amt" type="text" name="itemamount" class="form-control" value="100" placeholder="Amount" />
                    <label class="control-label" for="prf">Product Info</label>
                    <input id="prf" type="text" name="iteminfo" class="form-control" value="Test" placeholder="Product Info" />
                    <label class="control-label" for="email">E-Mail</label>
                    <input id="email" type="email" name="email" class="form-control" value="ibhargav547@gmail.com" placeholder="email" />
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12">
                    <h3>Payment Details</h3>
                    <br />
                    <label class="control-label" for="fname">Item Price</label>
                    <input id="fname" type="text" name="fname" class="form-control" value="Sai Bhargav" placeholder="Name" />
                    <label class="control-label" for="amt">Shipping Charges</label>
                    <input id="amt" type="text" name="itemamount" class="form-control" value="100" placeholder="Amount" />
                    <label class="control-label" for="prf">GST Charges</label>
                    <input id="prf" type="text" name="iteminfo" class="form-control" value="Test" placeholder="Product Info" />
                    <label class="control-label" for="paytype">Payment Type</label>
                    <select id="paytype" class="form-control">
                        <option id="#">-- Select Payment Type --</option>
                        <option value="cc">Credit Card</option>
                        <option value="dc">Debit Card</option>
                        <option value="nb">Net Banking</option>
                        <option value="upi">UPI</option>
                        <option value="emi">EMI</option>
                    </select>
                    <label class="control-label" for="email">Other Charges</label>
                    <input id="email" type="email" name="email" class="form-control" value="ibhargav547@gmail.com" placeholder="email" />
                </div>
            </div><br />
            @*<div class="row">
                <h3 id="headings" class="pull-right" style="margin-right:15%">Total Payable Amount:INR 642.65 </h3>
            </div>*@
            <div class="row">
                <div id="txnnote" class="col-lg-12 col-md-12 col-sm-12 pull-left">
                    <h4><u>Transaction fees for various modes of payment are as follows -</u></h4>
                    <p>
                        <ul>
                            <li>Net Banking : Rs.2.50/- per transaction</li>
                            <li>Debit Cards : 0.90% of the Bill Amount</li>
                            <li>Credit Cards and Other Payment Options : 1.00% of the Bill Amount</li>
                            <li>BharatQR - 0.85% of the Bill amount</li>
                            <li>Rupay Debit cards - Nil</li>
                            <li>UPI - Nil</li>
                            <text style="font-style:italic">(GST and other Govt levies applicable on Transaction fee would be charged extra)</text>
                        </ul>
                    </p>
                    <br />
                    <text style="color:red;text-align:justify;">
                        <strong><u>Note:</u></strong> There is a possibility of link getting disconnected, during returning from the BANK after successful debit from your bank account.
                        If this occurs, PLEASE DO NOT pay the bill again. The portal system, will receive the confirmation from the BANK within 2 working days,
                        after which it can be verified at the website
                        <br /><br />
                    </text>
                </div>
            </div>
            <br />
            <p class="text-center">** Auto-generated email will be sent on transaction status along with details **</p>
            <br /><br />
            <div class="row text-center">
                <input type="submit" value="Proceed to Pay" class="btn btn-success" />
                <a class="btn btn-danger" href="#">Cancel Transaction</a>
            </div>
            <br />
        </div>
        <hr style="border-top:2px solid grey;width:90%" />
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4">
                <img id="secureimage" class="img-thumbnail" src="~/Content/Images/securepayment.png" />
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <img id="secureimage" class="img-thumbnail" src="~/Content/Images/securepayment2.png" />
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4">
                <img id="secureimage" class="img-thumbnail" src="~/Content/Images/safe_secure.jpg" />
            </div>
        </div>

        <br /><br />
    </div>
}

    @*@using (Html.BeginForm("PaymentPage", "PaymentGatewayTransaction", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            <div class="row">
                <div class="col-lg-6">
                    <label class="control-label" for="fname">Name</label>
                    <input id="fname" type="text" name="fname" class="form-control" value="Sai Bhargav" placeholder="Name" />
                    <label class="control-label" for="amt">Amount</label>
                    <input id="amt" type="text" name="itemamount" class="form-control" value="100" placeholder="Amount" />
                    <label class="control-label" for="prf">Product Info</label>
                    <input id="prf" type="text" name="iteminfo" class="form-control" value="Test" placeholder="Product Info" />
                    <label class="control-label" for="email">E-Mail</label>
                    <input id="email" type="email" name="email" class="form-control" value="ibhargav547@gmail.com" placeholder="email" />
                    <br /><br />
                    <input type="submit" value="Proceed to Pay" class="btn btn-success" />
                    <a class="btn btn-danger" href="#">Cancel Transaction</a>
                </div>
                <br />
                <div id="txnnote" class="col-lg-6 col-md-12 col-sm-12 pull-left">
                    <h4><u>Transaction fees for various modes of payment are as follows -</u></h4>
                    <p>
                        <ul>
                            <li>Net Banking : Rs.2.50/- per transaction</li>
                            <li>Debit Cards : 0.90% of the Bill Amount</li>
                            <li>Credit Cards and Other Payment Options : 1.00% of the Bill Amount</li>
                            <li>BharatQR - 0.85% of the Bill amount</li>
                            <li>Rupay Debit cards - Ni</li>
                            <li>UPI - Nil</li>
                            <text style="font-style:italic">(GST and other Govt levies applicable on Transaction fee would be charged extra)</text>
                        </ul>
                    </p>
                    <br />
                    <text style="color:red;text-align:justify;">
                        <strong><u>Note:</u></strong> There is a possibility of link getting disconnected, during returning from the BANK after successful debit from your bank account.
                        If this occurs, PLEASE DO NOT pay the bill again. The portal system, will receive the confirmation from the BANK within 2 working days,
                        after which it can be verified at the website
                        <br /><br />
                    </text>

                </div>
            </div>
        </div>
    }*@

LearnMVC/Views/PaymentGatewayTransaction/PaymentStatus.cshtml
@{
    ViewBag.Title = "PaymentStatus";
}

<style>
    #tbltran{
        width:50%;
        margin-left:25%;
    }

    #c {
        background-color: midnightblue;
        color: white;
    }
</style>

<h2 id="headings">Payment Status</h2>

<hr />
<table id="tbltran" class="table table-bordered table-responsive text-center">
    <tr>
        <td colspan="2">
            <h4>Your @ViewBag.TranStatus</h4>
        </td>
    </tr>
    
    <tr>
        <td id="c">Transaction ID</td>
        <td>@ViewBag.OrderID.ToUpper()</td>
    </tr>
    <tr>
        <td id="c">Customer Name</td>
        <td>@ViewBag.Name</td>
    </tr>
    <tr>
        <td id="c">Paid Amount</td>
        <td>@ViewBag.Amount</td>
    </tr>
    <tr>
        <td id="c">Transaction Status</td>
        @if (ViewBag.Transtatus == "Payment is successful")
        {
            <td style="background-color:green;color:white">@ViewBag.Transtatus</td>
        }
        else
        {
            <td style="background-color:red;color:white">@ViewBag.Transtatus</td>
        }

    </tr>
</table>
<br />
<div class="text-center">
    <a class="btn btn-primary" href="javascript:window.print()">Print</a>
    <a class="btn btn-primary" href="~/Home/Index">Back to Home</a>
</div>